### ISSUE TITLE
Compiler Error in Code example

### ISSUE THREAD

**Issue by saeschdivara** [kobalicek/asmjit#85] opened 2015-05-20 12:34 UTC
// Read 'a' by using a memory operand having base register, index register
  // and scale. Translates to 'mov a, dword ptr [p + aIndex << 2]'.
  c.mov(a, ptr(p, aIndex, 2));

error: use of undeclared identifier 'ptr'

Can you please help me?

**Comment by kobalicek** [comment] 2015-05-20 12:39
Hi, it could be written as:

`c.mov(a, x86::ptr(p, aIndex, 2));`

There are in general two namespaces you can use - `asmjit` and `asmjit::x86` for operands construction.

Hope that helps and thanks, I will fix the docs.

**Comment by saeschdivara** [comment] 2015-05-20 12:51
Hey thanks for the fast update but now I got another compiler error:

In file included from ../test_hound_jit/main.cpp:11:
In file included from ../asmjit/src/asmjit/asmjit.h:368:
In file included from ../asmjit/src/asmjit/base.h:16:
../asmjit/src/asmjit/base/compiler.h:1399:45: error: no member named 'kId' in 'asmjit::TypeId<long>'
    static const uint32_t args[] = { T(P0), T(P1), T(P2) };
                                            ^
../asmjit/src/asmjit/base/compiler.h:1367:35: note: expanded from macro 'T'
#define T(_Type_) TypeId<_Type_>::kId
                                  ^
../test_hound_jit/main.cpp:20:28: note: in instantiation of member function 'asmjit::FuncBuilder3<int, const int *, long, long>::FuncBuilder3' requested here
  c.addFunc(kFuncConvHost, FuncBuilder3<int, const int*, intptr_t, intptr_t>());

Here is the line which will probably have caused the error (which is from the same example):
  // Function returning 'int' accepting pointer and two indexes.
  c.addFunc(kFuncConvHost, FuncBuilder3<int, const int*, intptr_t, intptr_t>());

Btw I am using clang compiler on OS X

**Comment by kobalicek** [comment] 2015-05-20 13:12
Could you point me to the example? I checked asmjit docs, but I don't see this construction being used. The problem is that you are using `FuncBuilder3` without specifying return and arguments. You should probably just use `FuncBuilder0<void>()`, but I don't know if that's what you want.

**Comment by saeschdivara** [comment] 2015-05-20 13:15
In the readme: Memory Addressing

**Comment by saeschdivara** [comment] 2015-05-20 13:23
Here is the full example:

```c++
#include <asmjit/asmjit.h>

using namespace asmjit;

int main(int tt, char* vv[]) {
  JitRuntime runtime;
  X86Compiler c(&runtime);

  // Function returning 'int' accepting pointer and two indexes.
  c.addFunc(kFuncConvHost, FuncBuilder3<int, const int*, intptr_t, intptr_t>());

  X86GpVar p(c, kVarTypeIntPtr, "p");
  X86GpVar aIndex(c, kVarTypeIntPtr, "aIndex");
  X86GpVar bIndex(c, kVarTypeIntPtr, "bIndex");

  c.setArg(0, p);
  c.setArg(1, aIndex);
  c.setArg(2, bIndex);

  X86GpVar a(c, kVarTypeInt32, "a");
  X86GpVar b(c, kVarTypeInt32, "b");

  // Read 'a' by using a memory operand having base register, index register
  // and scale. Translates to 'mov a, dword ptr [p + aIndex << 2]'.
  c.mov(a, x86::ptr(p, aIndex, 2));

  // Read 'b' by using a memory operand having base register only. Variables
  // 'p' and 'bIndex' are both modified.

  // Shift bIndex by 2 (exactly the same as multiplying by 4).
  // And add scaled 'bIndex' to 'p' resulting in 'p = p + bIndex * 4'.
  c.shl(bIndex, 2);
  c.add(p, bIndex);

  // Read 'b'.
  c.mov(b, x86::ptr(p));

  // a = a + b;
  c.add(a, b);

  c.ret(a);
  c.endFunc();

  // The prototype of the generated function changed also here.
  typedef int (*FuncType)(const int*, intptr_t, intptr_t);
  FuncType func = asmjit_cast<FuncType>(c.make());

  // Array passed to 'func'
  const int array[] = { 1, 2, 3, 5, 8, 13 };

  int x = func(array, 1, 2);
  int y = func(array, 3, 5);

  printf("x=%d\n", x); // Outputs "x=5".
  printf("y=%d\n", y); // Outputs "y=18".

  runtime.release((void*)func);
  return 0;
}
```

**Comment by saeschdivara** [comment] 2015-05-20 13:29
OK, I got it now to work:
´´´c++
c.addFunc(kFuncConvHost, FuncBuilder3<int, const char*, const char*, const char*>());
´´´

**Comment by kobalicek** [comment] 2015-05-20 13:57
Yeah,

The problem is that `intptr_t` is not recognized by function builder I guess (well it is, depending on platform). I will try to fix this. Temporarily you can use `void*` or `asmjit::IntPtrType`, both will work and are portable.

**Comment by kobalicek** [comment] 2015-05-20 13:57
`intptr_t` and `uintptr_t` not recognized by function builder.

**Comment by saeschdivara** [comment] 2015-05-20 14:03
Well ```c++ IntPtrType * ``` works but not ```c++ IntPtrType ``` alone

**Comment by saeschdivara** [comment] 2015-05-20 14:03
Also ```c++ const int * ``` works too

**Comment by kobalicek** [comment] 2015-05-21 08:47
Now the `IntPtrType` should work, I fixed it, but fixing real `intptr_t` will take me some time, have to figure it out first without breaking the current code.

**Comment by saeschdivara** [comment] 2015-05-21 08:56
Hey thanks, I will check it out soon and test it

**Comment by kobalicek** [comment] 2015-07-01 10:17
UPDATE: I fixed this completely in my local branch, will commit a fix soon.

**Comment by kobalicek** [comment] 2015-10-05 12:58
Fixes are now part of the next branch,

**Comment by saeschdivara** [comment] 2015-10-05 13:10
Nice :+1:

**Comment by kobalicek** [comment] 2015-10-12 09:43
Fixed in `next` branch.

**Closed by kobalicek** 2015-10-12 09:43 UTC
Labels: bug
