### ISSUE TITLE
CMakeLists.txt issues with setting of flags

### ISSUE THREAD

**Issue by blackbird8010** [kobalicek/asmjit#103] opened 2015-10-09 09:04 UTC
In `CMakeLists.txt`, starting at line 187, there are if statements trying to find out which flags to set and on which targets.

IMHO, this code does not what is intended to do for the following reasons:

(1) `If(${CMAKE_BUILD_TYPE})` seems to be there to check if the following `If()` has something sensible to work on. However, this check is always true (unless someone messes with `unset()`), since according to [the documentation](https://cmake.org/cmake/help/v3.0/variable/CMAKE_BUILD_TYPE.html), `CMAKE_BUILD_TYPE` seems to be defined for normal runs, and in addition: "Possible values are empty, Debug, Release, RelWithDebInfo and MinSizeRel.". In other words, with a normal `cmake . -DCMAKE_BUILD_TYPE=Debug`, the `Else()` is evaluated. If we remove the outer `If()`, cmake complains that `set_target_properties is called with incorrect number of arguments.` This must be because of the [set_target_properties](https://cmake.org/cmake/help/v3.0/command/set_source_files_properties.html) requiring `prop1 value1 [prop2 value2 [...]]`.

(2) In the `Else()` branch of the aforementioned `If()`, the flags are set globally, which makes cmake propagate the flags to other targets using `asmjit`. (In my case, `-fno-exceptions` is set to my source files, even though I do want to use exceptions in my code, just because I did a `add_subdirectory(asmjit)`, followed by a `target_link_libraries(... asmjit)`).

**Comment by kobalicek** [comment] 2015-10-09 13:23
I need to check this out, but I thought that if I configure for "VS" for example the `CMAKE_BUILD_TYPE` is empty and is then configured through the IDE, this is in contrast to using unix makefiles, where the build type has to be configured through command line.

Basically if `CMAKE_BUILD_TYPE` is empty and `If(${CMAKE_BUILD_TYPE})` passes it's wrong. I really hate cmake to be honest, the syntax doesn't make any sense for me

**Comment by blackbird8010** [comment] 2015-10-09 13:32
Not sure, but I think If(${VAR}) checks for Yes, 1, or TRUE, and not whether VAR is defined, nor does it check whether VAR is empty. Could that be?

**Comment by kobalicek** [comment] 2015-10-09 13:36
Apparently you are right, I just tested

```
Set(SOMEVAR "Test")
If(${SOMEVAR})
  Message("DEFINED")
Else()
  Message("UNDEFINED")
EndIf()
```

and it prints `UNDEFINED`. It shocks me :(

**Comment by kobalicek** [comment] 2015-10-09 13:36
strangely enough, when I do

```
Set(SOMEVAR "Test")
If(SOMEVAR)
  Message("DEFINED")
Else()
  Message("UNDEFINED")
EndIf()
```

it prints "DEFINED"

**Comment by kobalicek** [comment] 2015-10-09 13:47
So in the end it should be `If(CMAKE_BUILD_TYPE)`

**Comment by kirbyfan64** [comment] 2015-10-09 13:47
*This* is why I don't use CMake... :O

**Comment by kobalicek** [comment] 2015-10-09 13:49
I'm open to anything that doesn't cause build nightmares, cmake is mostly pain for devs themselves :)

**Comment by kobalicek** [comment] 2015-10-09 15:00
@blackbird8010 Do you have any suggestion of fixing the cflags propagation? I would like to fix this one as this is not the intention to propagate such flags to the parent.

**Comment by blackbird8010** [comment] 2015-10-09 17:48
Please see my pull request. If everything went well, I have not touched the MSVC stuff, which I cannot test.

**Comment by kobalicek** [comment] 2015-10-09 17:51
Will check it out. I'm playing with it and I'm now able to reproduce the issue with `set_source_files_properties` after using the lasest cmake on travis-ci (was a bit of pain to make it working).

**Comment by blackbird8010** [comment] 2015-10-09 18:00
I forgot to also handle the analogous code for the samples, since they are not built by default :( Also, cmake's caching behavior tricked me, so the else() is still not working on clang (nor gcc, see travis).

**Comment by kobalicek** [comment] 2015-10-10 01:14
I managed to make it working, now let's focus on fixing the cflags propagation. I renamed all `ASMJIT_CFLAGS` to `ASMJIT_PRIVATE_CFLAGS` to avoid a confusion when someone might think that these should be used when linking to asmjit (to setup includes for example). The only variables that I think can be used are `ASMJIT_DEPS` and `ASMJIT_LIBS`, which is intended for consumers and contains asmjit itself).

I think that I still do weird things that I include the project from other projects, this I would like to fix and make it a proper module, but I didn't find any cmake best practices tbh.

**Comment by kobalicek** [comment] 2015-10-10 12:07
To continue the discussion a bit. I would love to reduce the number of macros defined by asmjit in build.h and also passed to the C++ compiler. However, I also know from the past that every time I tried to make things simpler they have failed in some case. For example `ASMJIT_DEBUG` and `ASMJIT_RELEASE` are redundant, but I'm not sure if I can safely remove them and expect `NDEBUG` to always be defined when building a release build. I'm gonna investigate this a bit and see what I can do.

**Comment by kobalicek** [comment] 2015-10-10 14:47
@blackbird8010 Can you check the `next` branch if it works in your project? I'm now gonna check out your changes, but I think I cannot just merge as my changes completely changed the build file.

**Comment by kobalicek** [comment] 2015-10-10 14:48
I think that `-fnoexceptions` was propagated because it was `PUBLIC`, I changed all cflags to be `PRIVATE` to fix this. Maybe it would be worth to add one test that uses exceptions to see if this is working properly and nobody can break it in the future.

**Comment by blackbird8010** [comment] 2015-10-10 15:42
I checked with your `next` branch, with `-DCMAKE_BUILD_TYPE=Debug` resp. ` Release`, as well as with no specification of this variable at all. It works like a charm in all three cases (AppleClang, Mac)! Thanks a lot :)

(It was easy to adapt the existing code to the minor changes in the API.)

**Comment by kobalicek** [comment] 2015-10-10 15:45
Thanks! The changes are mostly cosmetic, I will merge once the X86Stream is finalized :)

**Comment by kobalicek** [comment] 2015-10-12 09:35
Closed, fixed in `next`.

**Closed by kobalicek** 2015-10-12 09:35 UTC
